name: Build and Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or whatever version you prefer

      - name: Install dependencies
        run: npm ci

      - name: Build site with 11ty
        run: npx @11ty/eleventy

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset
          git add _site/ -f
          git commit -m "Deploy to GitHub Pages"
          echo "Using token: ${{ secrets.GH_PAT }} | head -c 5"
          git push https://${{ secrets.GH_PAT }}@github.com/Citizen-Knowledge-Graph/ckg-site.git HEAD:gh-pages --force